# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0.xci
# IP: The module: 'axi_intc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0.xci
# IP: The module: 'axi_intc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_intc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
