# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard.xdc

# Block Designs: bd/axi_intc/axi_intc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc || ORIG_REF_NAME==axi_intc} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_axi_bram_ctrl_0_0/axi_intc_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==axi_intc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_xbar_0/axi_intc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_xbar_0 || ORIG_REF_NAME==axi_intc_xbar_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_axi_interconnect_0_0/axi_intc_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_interconnect_0_0 || ORIG_REF_NAME==axi_intc_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_axi_uartlite_0_0 || ORIG_REF_NAME==axi_intc_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_blk_mem_gen_0_0 || ORIG_REF_NAME==axi_intc_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_2 || ORIG_REF_NAME==axi_intc_auto_cc_2} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_3 || ORIG_REF_NAME==axi_intc_auto_cc_3} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_4 || ORIG_REF_NAME==axi_intc_auto_cc_4} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_0 || ORIG_REF_NAME==axi_intc_auto_cc_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_ds_0/axi_intc_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_ds_0 || ORIG_REF_NAME==axi_intc_auto_ds_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_m01_regslice_0/axi_intc_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_m01_regslice_0 || ORIG_REF_NAME==axi_intc_m01_regslice_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_cc_1 || ORIG_REF_NAME==axi_intc_auto_cc_1} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_ds_1/axi_intc_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_ds_1 || ORIG_REF_NAME==axi_intc_auto_ds_1} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_pc_0 || ORIG_REF_NAME==axi_intc_auto_pc_0} -quiet] -quiet

# IP: bd/axi_intc/ip/axi_intc_auto_rs_0/axi_intc_auto_rs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_intc_auto_rs_0 || ORIG_REF_NAME==axi_intc_auto_rs_0} -quiet] -quiet

# Block Designs: bd/clk_and_rst/clk_and_rst.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst || ORIG_REF_NAME==clk_and_rst} -quiet] -quiet

# IP: bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0_1/clk_and_rst_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_clk_wiz_0_1 || ORIG_REF_NAME==clk_and_rst_clk_wiz_0_1} -quiet] -quiet

# IP: bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_and_rst_proc_sys_reset_0_0 || ORIG_REF_NAME==clk_and_rst_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/axi_intc/axi_intc_ooc.xdc

# XDC: bd/clk_and_rst/clk_and_rst_ooc.xdc
