# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.cache/wt [current_project]
set_property parent.project_path C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/nimro/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/include
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default
} [current_fileset]
read_verilog {
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/common_defines.vh
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/pd_defines.vh
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/include/global.h
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/pic_map_auto.h
}
set_property is_global_include true [get_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/common_defines.vh]
set_property is_global_include true [get_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/pd_defines.vh]
set_property file_type "Verilog Header" [get_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/include/global.h]
set_property file_type "Verilog Header" [get_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/configs/snapshots/default/pic_map_auto.h]
read_verilog -library xil_defaultlib -sv {
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lib/beh_lib.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dbg/dbg.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/include/swerv_types.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec_decode_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec_gpr_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec_ib_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec_tlu_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dec/dec_trigger.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dma_ctrl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/exu/exu.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/exu/exu_alu_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/exu/exu_div_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/exu/exu_mul_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu_aln_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu_bp_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu_compress_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu_ifc_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/ifu/ifu_mem_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_addrcheck.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_bus_buffer.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_bus_intf.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_clkdomain.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_dccm_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_dccm_mem.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_ecc.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_lsc_ctl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_stbuf.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lsu/lsu_trigger.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/mem.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/lib/mem_lib.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/pic_ctrl.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dmi/rvjtag_tap.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/swerv.sv
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/swerv_wrapper.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/peripherals/bd/axi_intc/hdl/axi_intc_wrapper.v
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/peripherals/bd/clk_and_rst/hdl/clk_and_rst_wrapper.v
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dmi/dmi_jtag_to_core_sync.v
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/swerv_eh1/design/dmi/dmi_wrapper.v
  C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/design_top/swerv_eh1_reference_design.v
}
add_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/axi_intc.bd
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_bram_ctrl_0_0/axi_intc_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_xbar_0/axi_intc_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_axi_uartlite_0_0/axi_intc_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_blk_mem_gen_0_0/axi_intc_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_2/axi_intc_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_3/axi_intc_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_4/axi_intc_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_0/axi_intc_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_0/axi_intc_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_0/axi_intc_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_0/axi_intc_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_m01_regslice_0/axi_intc_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_m01_regslice_0/axi_intc_m01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_cc_1/axi_intc_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_1/axi_intc_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_1/axi_intc_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_ds_1/axi_intc_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_pc_0/axi_intc_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_rs_0/axi_intc_auto_rs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/ip/axi_intc_auto_rs_0/axi_intc_auto_rs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/axi_intc/axi_intc_ooc.xdc]

add_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/clk_and_rst.bd
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0_1/clk_and_rst_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0_1/clk_and_rst_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_clk_wiz_0_1/clk_and_rst_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/clk_and_rst_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/constrs_1/imports/constraints/zedboard.xdc
set_property used_in_implementation false [get_files C:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/constrs_1/imports/constraints/zedboard.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top swerv_eh1_reference_design -part xc7z020clg484-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef swerv_eh1_reference_design.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file swerv_eh1_reference_design_utilization_synth.rpt -pb swerv_eh1_reference_design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
