# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xci
# IP: The module: 'clk_and_rst_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xci
# IP: The module: 'clk_and_rst_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nimro/VivadoProjects/Cores-SweRV_fpga/hardware/project/script/eh1_zedboard/eh1_zedboard.srcs/sources_1/bd/clk_and_rst/ip/clk_and_rst_proc_sys_reset_0_0/clk_and_rst_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_and_rst_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
